import type { NextRequest } from "next/server"

export async function GET(req: NextRequest) {
  const { searchParams } = new URL(req.url)
  const city = searchParams.get("city") || "Thane"
  const type = searchParams.get("type") || "Government"
  const specialization = searchParams.get("specialization") || "General"

  // Simulate AI prediction delay
  await new Promise((resolve) => setTimeout(resolve, 1200))

  const predictions: Record<string, any> = {
    Thane: {
      predictedBeds: -19,
      topHospitals: [
        {
          rank: 34,
          name: "Jaigurudev Hospital",
          availableBeds: 347,
          totalBeds: 406,
          address: "Ghodbunder Road, Thane West",
          distance: "2.3 km",
          phone: "+91-22-2580-6000",
          type: "Private",
          doctorsOnDuty: 28,
          opdQueue: 12,
          bloodBank: { A: 45, B: 32, O: 58, AB: 18 },
          lastUpdated: "2:55:06 PM",
        },
        {
          rank: 40,
          name: "Super Speciality Hospital",
          availableBeds: 316,
          totalBeds: 332,
          address: "Pokhran Road No 2, Thane",
          distance: "3.1 km",
          phone: "+91-22-2534-7000",
          type: "Private",
          doctorsOnDuty: 22,
          opdQueue: 18,
          bloodBank: { A: 38, B: 28, O: 52, AB: 15 },
          lastUpdated: "2:54:32 PM",
        },
        {
          rank: 17,
          name: "Jag Pravesh Chandra Hospital",
          availableBeds: 277,
          totalBeds: 435,
          address: "Majiwada, Thane West",
          distance: "4.5 km",
          phone: "+91-22-2580-3000",
          type: "Government",
          doctorsOnDuty: 35,
          opdQueue: 24,
          bloodBank: { A: 52, B: 41, O: 68, AB: 22 },
          lastUpdated: "2:53:18 PM",
        },
        {
          rank: 33,
          name: "Max Super Speciality",
          availableBeds: 241,
          totalBeds: 325,
          address: "Manpada, Thane East",
          distance: "5.2 km",
          phone: "+91-22-6629-6000",
          type: "Private",
          doctorsOnDuty: 26,
          opdQueue: 15,
          bloodBank: { A: 42, B: 35, O: 61, AB: 19 },
          lastUpdated: "2:55:42 PM",
        },
        {
          rank: 96,
          name: "Bethany Hospital",
          availableBeds: 196,
          totalBeds: 478,
          address: "Naupada, Thane West",
          distance: "6.1 km",
          phone: "+91-22-2533-4000",
          type: "Trust",
          doctorsOnDuty: 38,
          opdQueue: 28,
          bloodBank: { A: 58, B: 46, O: 75, AB: 25 },
          lastUpdated: "2:52:55 PM",
        },
      ],
    },
    Delhi: {
      predictedBeds: 45,
      topHospitals: [
        {
          rank: 12,
          name: "AIIMS Delhi",
          availableBeds: 420,
          totalBeds: 500,
          address: "Ansari Nagar, New Delhi",
          distance: "5.2 km",
          phone: "+91-11-2658-8500",
          type: "Government",
          doctorsOnDuty: 65,
          opdQueue: 42,
          bloodBank: { A: 85, B: 72, O: 110, AB: 38 },
          lastUpdated: "2:54:15 PM",
        },
        {
          rank: 23,
          name: "Safdarjung Hospital",
          availableBeds: 380,
          totalBeds: 450,
          address: "Ring Road, New Delhi",
          distance: "7.8 km",
          phone: "+91-11-2673-0000",
          type: "Government",
          doctorsOnDuty: 58,
          opdQueue: 38,
          bloodBank: { A: 78, B: 65, O: 98, AB: 32 },
          lastUpdated: "2:53:48 PM",
        },
        {
          rank: 34,
          name: "Ram Manohar Lohia",
          availableBeds: 310,
          totalBeds: 400,
          address: "Baba Kharak Singh Marg",
          distance: "8.5 km",
          phone: "+91-11-2336-5525",
          type: "Government",
          doctorsOnDuty: 48,
          opdQueue: 32,
          bloodBank: { A: 65, B: 55, O: 88, AB: 28 },
          lastUpdated: "2:55:22 PM",
        },
        {
          rank: 45,
          name: "GTB Hospital",
          availableBeds: 280,
          totalBeds: 380,
          address: "Dilshad Garden, Delhi",
          distance: "12.3 km",
          phone: "+91-11-2232-3232",
          type: "Government",
          doctorsOnDuty: 42,
          opdQueue: 28,
          bloodBank: { A: 58, B: 48, O: 78, AB: 24 },
          lastUpdated: "2:52:38 PM",
        },
        {
          rank: 56,
          name: "Lok Nayak Hospital",
          availableBeds: 250,
          totalBeds: 350,
          address: "Jawaharlal Nehru Marg",
          distance: "9.1 km",
          phone: "+91-11-2323-4242",
          type: "Government",
          doctorsOnDuty: 38,
          opdQueue: 25,
          bloodBank: { A: 52, B: 42, O: 72, AB: 22 },
          lastUpdated: "2:54:58 PM",
        },
      ],
    },
    Mumbai: {
      predictedBeds: 32,
      topHospitals: [
        {
          rank: 8,
          name: "KEM Hospital",
          availableBeds: 390,
          totalBeds: 480,
          address: "Parel, Mumbai",
          distance: "3.5 km",
          phone: "+91-22-2410-7000",
          type: "Government",
          doctorsOnDuty: 62,
          opdQueue: 45,
          bloodBank: { A: 82, B: 68, O: 105, AB: 35 },
          lastUpdated: "2:53:12 PM",
        },
        {
          rank: 15,
          name: "Sion Hospital",
          availableBeds: 350,
          totalBeds: 420,
          address: "Sion, Mumbai",
          distance: "4.2 km",
          phone: "+91-22-2407-6301",
          type: "Government",
          doctorsOnDuty: 55,
          opdQueue: 38,
          bloodBank: { A: 72, B: 62, O: 95, AB: 32 },
          lastUpdated: "2:54:45 PM",
        },
        {
          rank: 22,
          name: "Nair Hospital",
          availableBeds: 320,
          totalBeds: 400,
          address: "Mumbai Central",
          distance: "5.8 km",
          phone: "+91-22-2302-7643",
          type: "Government",
          doctorsOnDuty: 48,
          opdQueue: 32,
          bloodBank: { A: 65, B: 55, O: 85, AB: 28 },
          lastUpdated: "2:52:28 PM",
        },
        {
          rank: 31,
          name: "JJ Hospital",
          availableBeds: 290,
          totalBeds: 370,
          address: "Byculla, Mumbai",
          distance: "6.5 km",
          phone: "+91-22-2373-5555",
          type: "Government",
          doctorsOnDuty: 42,
          opdQueue: 28,
          bloodBank: { A: 58, B: 48, O: 78, AB: 25 },
          lastUpdated: "2:55:18 PM",
        },
        {
          rank: 42,
          name: "Rajawadi Hospital",
          availableBeds: 260,
          totalBeds: 340,
          address: "Ghatkopar, Mumbai",
          distance: "11.2 km",
          phone: "+91-22-2510-0503",
          type: "Government",
          doctorsOnDuty: 38,
          opdQueue: 24,
          bloodBank: { A: 52, B: 42, O: 68, AB: 22 },
          lastUpdated: "2:53:52 PM",
        },
      ],
    },
    // Punjab Cities
    Chandigarh: {
      predictedBeds: 285,
      topHospitals: [
        {
          rank: 3,
          name: "Post Graduate Institute of Medical Education and Research (PGIMER)",
          availableBeds: 350,
          totalBeds: 1800,
          address: "Sector 12, Chandigarh",
          distance: "2.1 km",
          phone: "+91-172-274-6018",
          type: "Government",
          doctorsOnDuty: 320,
          opdQueue: 85,
          bloodBank: { A: 450, B: 380, O: 520, AB: 180 },
          lastUpdated: "2:54:15 PM",
          lat: 30.7649,
          lng: 76.7794,
        },
        {
          rank: 7,
          name: "Government Medical College and Hospital",
          availableBeds: 220,
          totalBeds: 1200,
          address: "Sector 32, Chandigarh",
          distance: "4.5 km",
          phone: "+91-172-266-5251",
          type: "Government",
          doctorsOnDuty: 240,
          opdQueue: 65,
          bloodBank: { A: 320, B: 280, O: 380, AB: 120 },
          lastUpdated: "2:55:32 PM",
          lat: 30.7021,
          lng: 76.7146,
        },
        {
          rank: 12,
          name: "Fortis Hospital Mohali",
          availableBeds: 70,
          totalBeds: 350,
          address: "Phase 8B, Mohali",
          distance: "8.3 km",
          phone: "+91-172-509-9999",
          type: "Private",
          doctorsOnDuty: 85,
          opdQueue: 35,
          bloodBank: { A: 120, B: 95, O: 140, AB: 45 },
          lastUpdated: "2:53:48 PM",
          lat: 30.6846,
          lng: 76.7185,
        },
        {
          rank: 18,
          name: "Ivy Hospital Mohali",
          availableBeds: 85,
          totalBeds: 280,
          address: "Phase 7, Mohali",
          distance: "9.1 km",
          phone: "+91-172-466-6000",
          type: "Private",
          doctorsOnDuty: 65,
          opdQueue: 28,
          bloodBank: { A: 95, B: 78, O: 110, AB: 38 },
          lastUpdated: "2:52:22 PM",
          lat: 30.7065,
          lng: 76.7140,
        },
        {
          rank: 25,
          name: "Max Super Speciality Hospital Mohali",
          availableBeds: 95,
          totalBeds: 300,
          address: "Phase 6, Mohali",
          distance: "11.5 km",
          phone: "+91-172-398-8888",
          type: "Private",
          doctorsOnDuty: 72,
          opdQueue: 32,
          bloodBank: { A: 105, B: 88, O: 125, AB: 42 },
          lastUpdated: "2:54:58 PM",
          lat: 30.6780,
          lng: 76.7250,
        },
      ],
    },
    Ludhiana: {
      predictedBeds: 195,
      topHospitals: [
        {
          rank: 5,
          name: "Dayanand Medical College",
          availableBeds: 170,
          totalBeds: 850,
          address: "Civil Lines, Ludhiana",
          distance: "1.8 km",
          phone: "+91-161-502-7856",
          type: "Government",
          doctorsOnDuty: 180,
          opdQueue: 55,
          bloodBank: { A: 220, B: 185, O: 260, AB: 95 },
          lastUpdated: "2:55:12 PM",
          lat: 31.6315,
          lng: 75.1298,
        },
        {
          rank: 9,
          name: "Christian Medical College Ludhiana",
          availableBeds: 150,
          totalBeds: 750,
          address: "Brown Road, Ludhiana",
          distance: "3.2 km",
          phone: "+91-161-503-9391",
          type: "Private",
          doctorsOnDuty: 160,
          opdQueue: 48,
          bloodBank: { A: 195, B: 165, O: 230, AB: 80 },
          lastUpdated: "2:53:45 PM",
          lat: 30.9023,
          lng: 75.8426,
        },
        {
          rank: 14,
          name: "Civil Hospital Ludhiana",
          availableBeds: 80,
          totalBeds: 500,
          address: "Punjab Agricultural University Campus, Ludhiana",
          distance: "5.5 km",
          phone: "+91-161-240-2411",
          type: "Government",
          doctorsOnDuty: 95,
          opdQueue: 45,
          bloodBank: { A: 150, B: 125, O: 180, AB: 65 },
          lastUpdated: "2:54:28 PM",
          lat: 30.9010,
          lng: 75.8573,
        },
        {
          rank: 21,
          name: "Sohana Hospital",
          availableBeds: 120,
          totalBeds: 350,
          address: "Gill Road, Ludhiana",
          distance: "7.8 km",
          phone: "+91-161-462-2121",
          type: "Private",
          doctorsOnDuty: 68,
          opdQueue: 32,
          bloodBank: { A: 125, B: 105, O: 145, AB: 48 },
          lastUpdated: "2:52:55 PM",
          lat: 30.8950,
          lng: 75.8220,
        },
        {
          rank: 28,
          name: "Deep Hospital",
          availableBeds: 95,
          totalBeds: 280,
          address: "Model Town, Ludhiana",
          distance: "9.3 km",
          phone: "+91-161-507-5555",
          type: "Private",
          doctorsOnDuty: 52,
          opdQueue: 28,
          bloodBank: { A: 88, B: 72, O: 102, AB: 35 },
          lastUpdated: "2:55:42 PM",
          lat: 30.9120,
          lng: 75.8350,
        },
      ],
    },
    Amritsar: {
      predictedBeds: 130,
      topHospitals: [
        {
          rank: 6,
          name: "Sri Guru Ram Das Hospital Amritsar",
          availableBeds: 130,
          totalBeds: 650,
          address: "Hall Bazar, Amritsar",
          distance: "2.5 km",
          phone: "+91-183-255-0301",
          type: "Government",
          doctorsOnDuty: 140,
          opdQueue: 42,
          bloodBank: { A: 175, B: 145, O: 200, AB: 70 },
          lastUpdated: "2:54:18 PM",
          lat: 31.6340,
          lng: 74.8723,
        },
        {
          rank: 11,
          name: "Amritsar Hospital",
          availableBeds: 110,
          totalBeds: 400,
          address: "Majitha Road, Amritsar",
          distance: "4.2 km",
          phone: "+91-183-502-7800",
          type: "Private",
          doctorsOnDuty: 95,
          opdQueue: 35,
          bloodBank: { A: 145, B: 120, O: 165, AB: 55 },
          lastUpdated: "2:55:32 PM",
          lat: 31.6420,
          lng: 74.8650,
        },
        {
          rank: 16,
          name: "Amandeep Hospital Jalandhar",
          availableBeds: 60,
          totalBeds: 300,
          address: "Nakodar Road, Jalandhar",
          distance: "85.3 km",
          phone: "+91-181-225-5600",
          type: "Private",
          doctorsOnDuty: 75,
          opdQueue: 32,
          bloodBank: { A: 95, B: 80, O: 115, AB: 40 },
          lastUpdated: "2:53:48 PM",
          lat: 31.3260,
          lng: 75.5762,
        },
        {
          rank: 22,
          name: "Emperor Hospital Amritsar",
          availableBeds: 85,
          totalBeds: 250,
          address: "Court Road, Amritsar",
          distance: "3.8 km",
          phone: "+91-183-502-4444",
          type: "Private",
          doctorsOnDuty: 58,
          opdQueue: 28,
          bloodBank: { A: 118, B: 98, O: 135, AB: 48 },
          lastUpdated: "2:52:22 PM",
          lat: 31.6380,
          lng: 74.8750,
        },
        {
          rank: 29,
          name: "Global Hospital Amritsar",
          availableBeds: 72,
          totalBeds: 200,
          address: "G.T. Road, Amritsar",
          distance: "6.1 km",
          phone: "+91-183-502-8888",
          type: "Private",
          doctorsOnDuty: 42,
          opdQueue: 25,
          bloodBank: { A: 92, B: 78, O: 108, AB: 38 },
          lastUpdated: "2:54:58 PM",
          lat: 31.6480,
          lng: 74.8580,
        },
      ],
    },
    Jalandhar: {
      predictedBeds: 165,
      topHospitals: [
        {
          rank: 4,
          name: "Amandeep Hospital Jalandhar",
          availableBeds: 60,
          totalBeds: 300,
          address: "Nakodar Road, Jalandhar",
          distance: "1.2 km",
          phone: "+91-181-225-5600",
          type: "Private",
          doctorsOnDuty: 75,
          opdQueue: 32,
          bloodBank: { A: 95, B: 80, O: 115, AB: 40 },
          lastUpdated: "2:55:05 PM",
          lat: 31.3260,
          lng: 75.5762,
        },
        {
          rank: 8,
          name: "Civil Hospital Jalandhar",
          availableBeds: 145,
          totalBeds: 450,
          address: "Ladowali Road, Jalandhar",
          distance: "3.8 km",
          phone: "+91-181-225-3234",
          type: "Government",
          doctorsOnDuty: 88,
          opdQueue: 38,
          bloodBank: { A: 135, B: 115, O: 155, AB: 52 },
          lastUpdated: "2:53:28 PM",
          lat: 31.3120,
          lng: 75.5780,
        },
        {
          rank: 13,
          name: "Jalandhar City Hospital",
          availableBeds: 95,
          totalBeds: 280,
          address: "Model Town, Jalandhar",
          distance: "5.5 km",
          phone: "+91-181-502-9999",
          type: "Private",
          doctorsOnDuty: 62,
          opdQueue: 28,
          bloodBank: { A: 105, B: 88, O: 125, AB: 42 },
          lastUpdated: "2:54:42 PM",
          lat: 31.3350,
          lng: 75.5680,
        },
        {
          rank: 19,
          name: "St. Soldier Hospital",
          availableBeds: 120,
          totalBeds: 350,
          address: "Cantonment, Jalandhar",
          distance: "7.2 km",
          phone: "+91-181-225-7001",
          type: "Government",
          doctorsOnDuty: 68,
          opdQueue: 32,
          bloodBank: { A: 118, B: 98, O: 135, AB: 48 },
          lastUpdated: "2:52:15 PM",
          lat: 31.3180,
          lng: 75.5820,
        },
        {
          rank: 26,
          name: "Narayana Hospital Jalandhar",
          availableBeds: 78,
          totalBeds: 220,
          address: "Phagwara, Jalandhar",
          distance: "12.8 km",
          phone: "+91-181-503-6666",
          type: "Private",
          doctorsOnDuty: 48,
          opdQueue: 25,
          bloodBank: { A: 85, B: 72, O: 98, AB: 35 },
          lastUpdated: "2:55:38 PM",
          lat: 31.1250,
          lng: 75.7650,
        },
      ],
    },
  }

  const result = predictions[city] || predictions.Thane

  return Response.json(result)
}
